import Head from 'next/head'
import { ReactElement, useEffect } from 'react'

export default function Home(): ReactElement {
  useEffect(() => {
    async function startExplorable() {
      const CinemacticStorie = (
        await import('experiences/explorables/cinematic/storie')
      ).default

      /* eslint-disable no-new */
      new CinemacticStorie(
        document.querySelector('canvas.webgl'),
        document.querySelector('#experience-01'),
      )

      new CinemacticStorie(
        document.querySelector('canvas.webgl-02'),
        document.querySelector('#experience-02'),
      )
    }

    startExplorable()
  }, [])

  return (
    <div>
      <Head>
        <title>Next Project Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className="text">
          <h1>Título!!</h1>
          <br />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />

          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />

          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
        </div>
        <div className="experience-container" id="experience-01">
          <canvas className="webgl"></canvas>
        </div>
        <div className="text">
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
        </div>
        <div className="experience-container" id="experience-02">
          <canvas className="webgl-02"></canvas>
        </div>
      </main>
    </div>
  )
}
