import Experience from 'experiences/dynamics/Experience'
import Head from 'next/head'
import { ReactElement, useEffect, useState } from 'react'

export default function Home(): ReactElement {
  const [, setExperience] = useState<Experience>(null)

  useEffect(() => {
    const exp = new Experience(
      document.querySelector('canvas.webgl'),
      document.querySelector('.experience-container'),
    )

    console.log(exp)

    setExperience(exp)
  }, [])

  return (
    <div>
      <Head>
        <title>Next Project Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className="text">
          <h1>Título!!</h1>
          <br />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />

          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <br />

          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
        </div>
        <div className="experience-container">
          <canvas className="webgl"></canvas>
        </div>
        <div className="text">
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem
            reiciendis adipisci earum aliquam expedita voluptatem iure culpa
            natus blanditiis beatae aliquid ut totam dolore cupiditate in
            doloremque, cum, mollitia eius.
          </p>
        </div>
      </main>
    </div>
  )
}
