# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run.
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   # push:
#   #   branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.5
#         with:
#           node-version: 12

#       - name: Setup yarn Package Manager
#         run: npm install -g yarn

#       - name: Install Project Dependecies
#         run: yarn install --frozen-lockfile

#       - name: Build Next App
#         run: yarn build

#       - name: Deploy Next App to Google App Engine
#         id: deploy
#         uses: google-github-actions/deploy-appengine@main
#         with:
#           credentials: ${{ secrets.GCP_APP_CREDENTIALS }}

#       - name: Test browser output
#         id: test
#         run: curl "${{ steps.deploy.outputs.url }}"
